backend:
  name: git-gateway

# when using the default proxy server port
# local_backend:
#   # when using a custom proxy server port
#   url: http://localhost:8082/api/v1
#   # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
#   allowed_hosts: ['192.168.0.1']

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - label: "Home Page"
    name: "homepage"
    files:
      - label: "Home Page"
        name: "Home Page"
        file: "site/content/home.json"
        fields:
          - {label: "Intro Text", name: intro, widget: string}
          - {label: "Intro Homepage Background", name: introHomePageBackground, widget: image}
          - label: Sections
            name: sections
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: Photo, name: photo, widget: image}              
              - {label: Learn More, name: learnMore, widget: boolean, default: false}
              - {label: Slug, name: slug, widget: string}

  - label: "Site Config"
    name: "site-config"
    files:
      - label: "Footer"
        name: "footer"
        file: "site/content/footer.json"
        fields:
          - {label: "Phone", name: phone, widget: string}
          - {label: "Address", name: address, widget: string}
          - {label: "Facebook", name: facebook, widget: string}
          - {label: "Instagram", name: instagram, widget: string}
          - {label: "Twitter", name: twitter, widget: string}

  - label: "Pages"
    name: "pages"
    folder: "site/content/pages"
    create: true
    fields: 
        - {label: Title, name: title, widget: string}
        - {label: Slug, name: slug, widget: string}
        - {label: "Intro Text", name: intro, widget: string}
        - label: Slider
          name: sliderImage
          widget: list
          fields:
              - {label: "Slider Background", name: sliderBackground, widget: image}
        - {label: "Description", name: description, widget: string}
        - {label: "Section First Topic", name: sectionFirstTopic, widget: string }
        - {label: "Section First Topic Detail", name: sectionFirstTopicDetail, widget: string }
        - {label: "Section First Topic Heading 1", name: sectionFirstTopicHeading1, widget: string }
        - {label: "Section First Topic Img 1", name: sectionFirstTopicImg1, widget: image }
        - {label: "Section First Topic Heading 2", name: sectionFirstTopicHeading2, widget: string }
        - {label: "Section First Topic Img 2", name: sectionFirstTopicImg2, widget: image }
        - {label: "Section First Topic Heading 3", name: sectionFirstTopicHeading3, widget: string }
        - {label: "Section First Topic Img 3", name: sectionFirstTopicImg3, widget: image }
        - {label: "Section Second Topic", name: sectionSecondTopic, widget: string}
        - {label: "Section Second Topic Detail", name: sectionSecondTopicDetail, widget: string}
        - {label: "Section Second Topic Plan", name: sectionSecondTopicPlan, widget: string}
        - {label: "Section Background Img 1", name: sectionBackgroundImg1, widget: image }
        - {label: "Section Background Img 2", name: sectionBackgroundImg2, widget: image }
        - {label: "Section Third Topic", name: sectionThirdTopic, widget: string}
        - {label: "Section Third Topic Heading", name: sectionThirdTopicHeading, widget: string}
        - {label: "Section Third Topic Img", name: sectionThirdTopicImg, widget: image }
        - {label: "Section Third Topic Detail", name: sectionThirdTopicDetail, widget: markdown}
        - {label: "Section Last Img", name: sectionLastImg, widget: image }
        - {label: "Section Last Img Text", name: sectionLastImgText, widget: markdown}
          



